</td></tr>
<tr><td height=20 colSpan=5 align="center" valign="middle" background="llblue.jpg" style="background-repeat: repeat-y;">
<label id="result"></label></td>
<tr><td colSpan=5 align="right" valign="middle" background="llblue.jpg" style="background-repeat: repeat-y; font-size:30px">
<a href="javascript:history.back();">·µ»Ø<img src="back.png" width="30" height="28" /></a></td></tr></tr></table></div></body></html>
