<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head><title>LED屏显示控制系统</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
</head>
<style> 
body{ text-align:center; font-size:40px} 
.div{ margin:0 auto; width:833px; height:470px}
.tbs { height:50px; font-size:35px;}
.td{ border-bottom:1px solid #000080; border-right:1px solid #000080}
</style>
<body  bgColor=#ffffff leftMargin=0 topMargin=10 marginwidth="0" marginheight="0">
<div align=center class=div>
<table style="border:1px solid #000080" height=482 cellSpacing=0 cellPadding=0 width="815">
<tr bgColor=#EEEEEE>
<td style="border-bottom: 1px solid #000080" vAlign=middle noWrap height=60 margin=50 width="559">
<h3 align="center"><font color="#006699">定时浇花控制系统</font></h3></td>
<td style="border-bottom: 1px solid #000080" vAlign=center noWrap height=60 width="165"><img src="logo.png" width="139" height="57" /></td>
<td style="border-bottom: 1px solid #000080" align=center vAlign=center noWrap width="89"> 
<a href="index.htm"><img border="0" src="home.png" width="55" height="53"></a></td></tr>
<tr><td colSpan=5 height=380 vAlign=top background="llblue.jpg" style="background-repeat: repeat-y;">