<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=GB2312" />
<title>LED屏显示控制系统</title>
<style type="text/css">
a:link {text-decoration: none;color: #FFF;}
a:visited {text-decoration: none;color: #FFF;}
a:hover {text-decoration: none;}
a:active {text-decoration: none;color: #FFF;}
.tbs {height:50px;font-size:35px;}
.topBK{background-color: #0080C0;}
.buttonBK{background-color:#09F}
.td{ border-bottom:1px solid #000080;border-left:1px solid #000080}
</style></head>
<body background="llblue.jpg" style="background-repeat:repeat-y;font-size:40px;">
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
<tr class="topBK"><td width="15%" height="30" align="center" valign="middle" >
<a href="javascript:history.back();">返回</a></td>
<td width="69%" align="center" valign="middle" >&nbsp;</td>
<td width="16%" align="center" valign="middle" ><a href="index1.htm">主页</a></td></tr></table>